spring:
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
zuul:
  #全部服务忽略敏感头（全部服务都可以使用cookie）
  sensitive-headers:
  routes:
    myProductA:
      path: /myProduct5/**
      serviceId: product
      sensitiveHeaders: 
    #简洁写法【不按默认的路由规则，自定义路由】
    #product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
#方法过时
management:
  security:
    enabled: false
